### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by dhanapalschandran** [matik12/aurelia-oauth#13]
This is not suporting cross origin request

**Comment by benhathaway** [comment]
This issue stems from this piece of code:
```        
    function OAuthInterceptor(oauthTokenService, eventAggregator) {
            var _this = this;
            this.oauthTokenService = oauthTokenService;
            this.eventAggregator = eventAggregator;
            this.request = function (config) {
                if (config.url.indexOf(window.location.origin) > -1) {    //  <-- HERE
                    return config;
                }
           ....
```
Is this a decision by design? I can see that we wouldn't want to spew our our bearer token for every request to every external resource - but in my scenario, I have a set of 5 APIs running in 5 different domains that all share a single OAuth Authentication subsystem. 

It would make sense to implement a whitelist of valid domains maybe.... or to allow the HttpClient.config() call to override the default behaviour and flag that it should indeed include the bearer token for this domain...

I am considering forking this code into a version that support CORS.... what do people think?

Regards,

Ben.

**Comment by matik12** [comment]
@dhanapalschandran can you explain what is your use case? 

@benhathawaydatum according to the piece of code you mentioned, this should all work well with even 10  different apis if they aren't exposed using the same origin. In case where your apis are hosted under the same domain this could be an issue preventing an interceptor from adding authorization header, so the if statement could be removed. 
The design decision that was made during this implementation assumed that, you host your web app under one domain, so it is basically a site with static html, js and assets and then in your web app you call the api or apis from different domains i,e, app,io & app-api.io etc. This would mean that, you do not need to add token when your web app is requesting static content as html etc. I hope this make sense right now.

**Comment by matik12** [comment]
@dhanapalschandran please check the latest plugin version and confirm that your issue still exists.

@benhathawaydatum the code part you mentioned above was removed, because it is no longer needed.

**Comment by benhathaway** [comment]
@matik12 Thank you Mateusz - that is great. I haven't checked out the latest version yet - but I certainly will.
I had planned to implement a way to configure a whitelist of API endpoints that would receive this token - so as to avoid sending out internal tokens to 3rd party APIs that we might try to integrate with... That is not a feature I actually need at the moment though, so... YAGNI.

**Comment by dhanapalschandran** [comment]
HI matik,

  I am using the aurelia-oauth created by you, which is working very well,
but now i need to get the bearer token to pass it in url for video
streaming, could you let me know whether i can get the bearer token using
your service.

Regards,
Dhanapal Chandran

**Comment by matik12** [comment]
Hi @dhanapalschandran,

thanks for kind words. 
Sure, you can import OAuthTokenService in the code i.e. `import { OAuthTokenService } from 'aurelia-oauth';` inject it into class and then use API methods such as getToken() or getAuthorizationHeader(). The second one will return a string in format `Bearer xxjwt.xxa....`

![image](https://user-images.githubusercontent.com/1382921/28372076-09fb7608-6c9f-11e7-92c6-4b6acf3ebfc9.png)

Thanks and take care,
Mat

**Comment by dhanapalschandran** [comment]
Thanks a lot for your prompt reply.

Regards,
Dhanapal Chandran

**Comment by dhanapalschandran** [comment]
HI Matik,

 How can i test the token expiry in aurelia-oAuth, I have requirement to
show popup if the token expired.

 Could you guide me in this.

Regards,
Dhanapal Chandran
