### ISSUE TITLE
One-shot config

### ISSUE THREAD

**Issue by PeterWone** [matik12/aurelia-oauth#3]
The auth-service config method appears to be _deliberately_ one-shot. This makes it impossible to change providers without restarting the Aurelia app. I'm looking at changing this, is there a reason I should leave it alone?

**Comment by matik12** [comment]
Hi **PeterWone**

when I was implementing this plugin, the intend was to support only one particular provider for current application. This scenario is the most common in business apps etc. where you have only one identity server supporting authorization and you don't need to support more then one oauth endpoint. Having this in mind, auth-service and auth-token-service both have configure method that should be invoke in the application start to configure plugin properly. 

My questions is why do you want to change providers when the application is running?

If this could be possible, I need to rethink the design and solution to support changing providers after application start. I have some concerns what should happen when you change provider, redirect to the login page, remove stored token ect? 

Thanks
Mat

**Comment by PeterWone** [comment]
The use-case you describe I call "enterprise internal". In this case all the users are employees. Another use-case is "enterprise external" where the users are either employed by another company or are customers. In this case you cannot expect to know the provider before the app starts. It is likely that users will choose the wrong provider and want to change their selection but there is no reason to change provider once a token has been issued. I have already made experimental modifications that seem to work. An unrelated possible problem is lack of provider support for implicit flow, the only Microsoft documentation I can find is for auth flow.

**Comment by matik12** [comment]
**PeterWone**

thanks for input on that topic, it seems you worked it out to suit your scenario. I hope this should be straight forward to delay plugin flow until user choose/change identity provider. 
According to problem with providers, I believe most of them support implicit grant flow which is recommended for SPA and mobile apps, thus this maybe not be a big issue. 

Can we  then close this issue?

Thanks
Mat
